# -*- coding: utf-8 -*-
"""Bill & BMI Calculator .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0HkMlxsq15DapTi6L4p-5p8ftTZHwlL
"""

i = 0
while i < 10:
   i += 1
   print(i)

print("Hello, " + input("What is your name?") + "!")

len(("Tonny"))

type(True)

print("Number of characters in your name is: " + str(len(input("What is your name?"))))

6 / 4

2 ** 3

3 * (3 + 3) / 3 - 3

height = float(input("Please Enter your height in m: "))
weight = float(input("Please Enter your weight in kg: "))

bmi = round(weight / height**2,2)
if bmi < 18.5:
  print(f"Your BMI is {bmi}, you are underweight.")
elif bmi < 25:
  print(f"Your BMI is {bmi}, you have a normal weight.")
elif bmi < 30:
  print(f"Your BMI is {bmi}, you are slightly overweight.")
elif bmi < 35:
  print(f"Your BMI is {bmi}, you are obese.")

# f-string

score = 0
height = 1.88
isWinning = True

print(f"your score is {score}, your height is {height}, you are winning is {isWinning}")

a = int("5") / int(2.7)
print(type(a))

# Bill calculator

print("Welcome to the tip calculator!")
bill = int(input("What was the total bill?"))
percentagetip = int(input("How much tip would you like to give? 10, 12, or 15?"))

if percentagetip == 10:
  bill = bill * 1.10
elif percentagetip == 12:
  bill = bill * 1.12
elif percentagetip == 15:
  bill = bill * 1.15
else:
  print("Invalid input")
people = int(input("How many people to split the bill?"))
bill = bill / people
print(f"Each person should pay: {bill}")

# check whether a number is even

print("Checking if a number is odd or Even")
number  = int(input("Please enter a number:"))
# using a modulo operator
if number % 2 == 0:
  print(f"The number {number}, is an even number")
else:
  print(f"The number {number}, is an odd")

# if else statements - roller coaster

bill = 0

height = float(input("Please Enter your height in cm: "))
if height >= 120:
  print("You can ride the roller coaster")
  age = int(input("Please Enter your age: "))
  if age <= 12:
    bill = 5
    print("The child tickets are $5")
  elif age <= 18:
    bill = 7
    print("Youths tickets are $7")
  else:
    bill = 12
    print("Adult tickets are $12.")
  photo_check = input("Do you want a photo taken? Y or N")
  if photo_check == "Y":
    bill += 3
  print(f"Please pay ${bill}")
else:
  print("Sorry, You must be over 120cm to ride")

# Pizaa

print("Welcome to Pythin Pizza Deliveries")
size = input("What size pizza do you want? S, M, or L: ")
pepperoni = input("Do you want pepperoni? Y or N: ")
extra_cheese = input("Do you want extra cheese? Y or N: ")
bill = 0

if size == 'S':
  bill += 15
elif size == 'M':
    bill += 20
elif size == 'L':
  bill += 25
else:
  print("wrong input")
if pepperoni == 'Y':
  if size == 'S':
    bill += 2
  else:
    bill += 3
if extra_cheese == 'Y':
  bill += 1
print(f"your total bill is ${bill}")



